# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('text', models.TextField(default='')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('source', models.URLField(default='http://w3c.com')),
            ],
        ),
    ]
