# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poemUser', '0001_initial'),
        ('tags', '0001_initial'),
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poemUser.PoemUser'),
        ),
        migrations.AddField(
            model_name='poem',
            name='tags',
            field=models.ManyToManyField(default=None, to='tags.Tag'),
        ),
    ]
