# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_auto_20160711_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='novotes',
            field=models.IntegerField(default=0),
        ),
    ]
