# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_auto_20170105_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poem',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, related_name='comments', to='poem.Comment'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(default='', max_length=75),
        ),
    ]
