# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 04:54
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0012_remove_poem_tags2'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
