# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 01:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewTime', models.DateTimeField(verbose_name='date viewed')),
            ],
        ),
        migrations.CreateModel(
            name='PoemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(verbose_name='date created')),
                ('safeMode', models.BooleanField(default=False)),
                ('preferences', models.ManyToManyField(to='tags.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poemUser.PoemUser'),
        ),
        migrations.AddField(
            model_name='history',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Poem'),
        ),
    ]
