# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poemuser',
            name='creationDate',
        ),
        migrations.AlterField(
            model_name='poemuser',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
