# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poemUser', '0002_auto_20160711_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='owner',
        ),
        migrations.AddField(
            model_name='history',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poemuser',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poemUser.History'),
        ),
    ]
