# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poemUser', '0003_auto_20160811_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poemuser',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poemUser.PoemUser'),
        ),
        migrations.AlterField(
            model_name='history',
            name='vote',
            field=models.IntegerField(),
        ),
    ]
