# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poemUser', '0004_auto_20160812_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='poemUser.PoemUser'),
        ),
        migrations.AlterField(
            model_name='history',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='poem.Poem'),
        ),
        migrations.AlterField(
            model_name='history',
            name='viewTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date viewed'),
        ),
    ]
