# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemUser', '0006_auto_20160812_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemuser',
            name='queue',
            field=models.TextField(default='{}'),
        ),
    ]
