# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_auto_20160711_0316'),
        ('poemUser', '0007_poemuser_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadPoem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date viewed')),
                ('viewDuration', models.FloatField(default=0)),
                ('vote', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='poemUser.PoemUser')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='poem.Poem')),
            ],
        ),
        migrations.RemoveField(
            model_name='view',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='view',
            name='poem',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
