# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemUser', '0009_auto_20160812_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemuser',
            name='similar',
            field=models.ManyToManyField(blank=True, related_name='_poemuser_similar_+', to='poemUser.PoemUser'),
        ),
    ]
