# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemUser', '0010_poemuser_similar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poemuser',
            name='similar',
            field=models.ManyToManyField(default=None, related_name='_poemuser_similar_+', to='poemUser.PoemUser'),
        ),
    ]
