# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poemUser', '0013_auto_20170105_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poemuser',
            name='preferences',
        ),
    ]
