# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 04:35
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poemUser', '0014_remove_poemuser_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='poemuser',
            name='preferences',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
