# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20170114_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='tagName',
            field=models.CharField(default='poem', max_length=200, unique=True),
        ),
    ]
