# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20170114_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagName',
            new_name='name',
        ),
    ]
